/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#fbfbe2',
        surface: '#fbfbe2',
        'surface-bright': '#fbfbe2',
        'surface-dim': '#dbdcc3',
        'surface-container': '#efefd7',
        'surface-container-low': '#f5f5dc',
        'surface-container-high': '#eaead1',
        'surface-container-highest': '#e4e4cc',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e4e4cc',
        'on-surface': '#1b1d0e',
        'on-surface-variant': '#56423d',
        'on-background': '#1b1d0e',
        outline: '#89726c',
        'outline-variant': '#dcc0b9',
        primary: '#9a4025',
        'primary-container': '#ba573b',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'primary-fixed': '#ffdbd1',
        'primary-fixed-dim': '#ffb5a0',
        secondary: '#486730',
        'secondary-container': '#c9eea9',
        'secondary-fixed': '#c9eea9',
        'secondary-fixed-dim': '#aed18f',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#4e6d36',
        'inverse-surface': '#303221',
        'inverse-on-surface': '#f2f2d9',
        'inverse-primary': '#ffb5a0',
        tertiary: '#745800',
        'tertiary-container': '#926f00',
        'tertiary-fixed': '#ffdf98',
        'tertiary-fixed-dim': '#f5bf22',
        'on-primary-fixed-variant': '#7e2b12',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        brand: '#9a4025',
        'brand-dark': '#7e2b12',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        headline: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ['Montserrat', 'system-ui', 'sans-serif'],
        label: ['Montserrat', 'system-ui', 'sans-serif'],
        /* Stitch code.html aliases */
        'display-lg': ['"Playfair Display"', 'Georgia', 'serif'],
        'display-lg-mobile': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-md': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-sm': ['"Playfair Display"', 'Georgia', 'serif'],
        'body-md': ['Montserrat', 'system-ui', 'sans-serif'],
        'body-lg': ['Montserrat', 'system-ui', 'sans-serif'],
        'label-md': ['Montserrat', 'system-ui', 'sans-serif'],
        caption: ['Montserrat', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      spacing: {
        gutter: '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'section-gap': '80px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
        custom: '12px',
      },
      keyframes: {
        slideFormIn: {
          '0%':   { opacity: '0', transform: 'translateX(-40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideFormOut: {
          '0%':   { opacity: '1', transform: 'translateX(0)' },
          '100%': { opacity: '0', transform: 'translateX(40px)' },
        },
        slideImageIn: {
          '0%':   { opacity: '0', transform: 'scale(1.05)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        fadeUp: {
          '0%':   { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideIn: {
          '0%':   { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        navFadeIn: {
          '0%':   { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        navImageIn: {
          '0%':   { opacity: '0', transform: 'scale(1.03)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        heroReveal: {
          '0%':   { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'slide-form-in':  'slideFormIn 0.6s cubic-bezier(0.16,1,0.3,1) forwards',
        'slide-form-out': 'slideFormOut 0.4s cubic-bezier(0.16,1,0.3,1) forwards',
        'slide-image-in': 'slideImageIn 0.8s cubic-bezier(0.16,1,0.3,1) forwards',
        'fade-up':        'fadeUp 0.6s cubic-bezier(0.16,1,0.3,1) forwards',
        'slide-in':       'slideIn 0.3s cubic-bezier(0.16,1,0.3,1) forwards',
        'nav-fade-in':    'navFadeIn 0.4s ease-out forwards',
        'nav-image-in':   'navImageIn 0.6s ease-out forwards',
        'hero-reveal':    'heroReveal 0.8s cubic-bezier(0.16,1,0.3,1) forwards',
      },
    },
  },
  plugins: [],
}
